[package]
name = "stw3"
version = "0.1.0"
authors = ["Lolirofle <lolipopple@hotmail.com>"]

[dependencies]
alga     = "0.5"
amethyst = {git = "https://github.com/amethyst/amethyst.git" , rev = "54af316b9ae11b7ca349ee14b16b6ffc4b48fc65"}#"0.4"
nalgebra = "0.13"
ncollide = "0.13"
