[package]
name = "stw3"
version = "0.1.0"
authors = ["Lolirofle <lolipopple@hotmail.com>"]

[dependencies]
alga     = "0.5"
amethyst = "0.5"
amethyst_input = "0.1"
amethyst_renderer = "0.5"
nalgebra = "0.13"
ncollide = "0.13"
futures = "0.1"
